//
// Created by dzevi on 13.11.2023.
//

#ifndef TWO_DIMENSIONAL_ARRAY_CLEANING_TWO_DIMENSIONAL_ARRAY_CLEANING_1000_H
#define TWO_DIMENSIONAL_ARRAY_CLEANING_TWO_DIMENSIONAL_ARRAY_CLEANING_1000_H

#endif //TWO_DIMENSIONAL_ARRAY_CLEANING_TWO_DIMENSIONAL_ARRAY_CLEANING_1000_H
